import "server-only";

import { appendSheetRow, ensureSheetExists, getSheetCell, getSheetRows, updateSheetRow } from "./google-sheets";
import { generateCompanyRsaReport } from "./openai-rsa";
import { parseJobDescription, splitSkillText } from "./jd-parser";
import type {
  RsaAdminInputs,
  RsaApplicationStudent,
  RsaApplicationsSummary,
  RsaCompanyDetails,
  RsaReportRecord,
  RsaStats,
  RsaStatus,
} from "./rsa-types";

const COMPANY_SHEET_NAME = "Company_tracking";
const APPLICATIONS_SHEET_NAME = "Applications";
const RSA_SHEET_NAME = "RSA_Reports";

export const RSA_REPORT_HEADERS = [
  "RSA ID",
  "Company ID",
  "Company Name",
  "Generated Date",
  "Generated By",
  "Candidate Sharing Strategy",
  "Interview Focus",
  "Company Expectations",
  "Training Gap",
  "Additional Admin Notes",
  "Tags",
  "Total Applications",
  "Selected Count",
  "Rejected Count",
  "In Progress Count",
  "Dropped Count",
  "AI Generated RSA",
  "Final Edited RSA",
  "Status",
  "Confirmed At",
  "Updated At",
] as const;

export async function getRsaOverview(companyId: string) {
  const company = await getCompanyFromCompanySheet(companyId);

  if (!company) {
    return null;
  }

  const applications = await getApplicationsForCompany(companyId);
  const applicationsSummary = summarizeApplications(applications);
  const stats = calculateStats(applicationsSummary);
  const history = await getRsaReportsForCompany(companyId);

  return {
    company,
    stats,
    existingRsa: history[0] ?? null,
    history,
    applicationsSummary,
  };
}

export async function getLatestRsaForCompany(companyId: string) {
  const history = await getRsaReportsForCompany(companyId);
  return history[0] ?? null;
}

export async function getAllRsaReports() {
  const sheet = await readRsaSheet();

  return sheet.rows
    .map(rowToRsaReport)
    .filter((report): report is RsaReportRecord => Boolean(report))
    .sort(sortReportsNewestFirst);
}

export async function getRsaReportsForCompany(companyId: string) {
  const reports = await getAllRsaReports();

  return reports
    .filter((report) => report.companyId === companyId)
    .sort(sortReportsNewestFirst);
}

export async function generateAndSaveCompanyRsa(input: {
  companyId: string;
  adminInputs: RsaAdminInputs;
}) {
  const overview = await getRsaOverview(input.companyId);

  if (!overview) {
    throw new Error("Company not found.");
  }

  const generatedRsa = await generateCompanyRsaReport({
    company: overview.company,
    stats: overview.stats,
    applicationsSummary: overview.applicationsSummary,
    adminInputs: input.adminInputs,
  });

  const report = await saveRsaReport({
    company: overview.company,
    adminInputs: input.adminInputs,
    stats: overview.stats,
    aiGeneratedRsa: generatedRsa,
    finalEditedRsa: generatedRsa,
    status: "Generated",
  });

  return {
    company: overview.company,
    stats: overview.stats,
    applicationsSummary: overview.applicationsSummary,
    generatedRsa,
    report,
  };
}

export async function saveRsaDraft(input: {
  companyId: string;
  rsaId?: string;
  adminInputs: RsaAdminInputs;
  aiGeneratedRsa: string;
  finalEditedRsa: string;
}) {
  const overview = await getRsaOverview(input.companyId);

  if (!overview) {
    throw new Error("Company not found.");
  }

  return saveRsaReport({
    rsaId: input.rsaId,
    company: overview.company,
    adminInputs: input.adminInputs,
    stats: overview.stats,
    aiGeneratedRsa: input.aiGeneratedRsa,
    finalEditedRsa: input.finalEditedRsa,
    status: "Draft",
  });
}

export async function confirmRsa(input: {
  companyId: string;
  rsaId?: string;
  adminInputs: RsaAdminInputs;
  aiGeneratedRsa: string;
  finalEditedRsa: string;
}) {
  const overview = await getRsaOverview(input.companyId);

  if (!overview) {
    throw new Error("Company not found.");
  }

  return saveRsaReport({
    rsaId: input.rsaId,
    company: overview.company,
    adminInputs: input.adminInputs,
    stats: overview.stats,
    aiGeneratedRsa: input.aiGeneratedRsa,
    finalEditedRsa: input.finalEditedRsa,
    status: "Confirmed",
  });
}

async function getCompanyFromCompanySheet(
  companyId: string,
): Promise<RsaCompanyDetails | null> {
  const sheet = await getSheetRows(COMPANY_SHEET_NAME);

  if (sheet.skipped) {
    throw new Error(sheet.reason ?? "Unable to read Company_tracking sheet.");
  }

  const row = sheet.rows.find(
    (item) => getSheetCell(item, ["Company ID", "CompanyID"], 11) === companyId,
  );

  if (!row) {
    return null;
  }

  const jd = cell(row, ["JD", "Job Description", "JD Details"], 3);
  const parsed = jd && !isUrl(jd) ? parseJobDescription(jd) : null;
  const name =
    cell(row, ["Company Name", "Company", "Name"], 1) ||
    parsed?.companyName ||
    companyId;
  const role =
    cell(row, ["Role", "JD Title", "Job Role"], 12) ||
    parsed?.role ||
    firstLine(jd) ||
    "Job Description";
  const techStack =
    cell(row, ["Tech Stack", "Skills", "Skills Required"], 2) ||
    parsed?.skillsRequired.join(", ") ||
    "";

  return {
    id: companyId,
    name,
    role,
    jdDetails: parsed?.raw || jd,
    jdLink: isUrl(jd) ? jd : "",
    expectedSkills: splitSkillText(techStack),
    location: cell(row, ["Location"], 6) || parsed?.location || "",
    crm: cell(row, ["CRM"], 5),
    currentStatus: cell(row, ["Status", "Current Status"], 9),
    remarks: cell(row, ["Remarks"], 10) || parsed?.remarks || "",
  };
}

async function getApplicationsForCompany(companyId: string) {
  const sheet = await getSheetRows(APPLICATIONS_SHEET_NAME);

  if (sheet.skipped) {
    throw new Error(sheet.reason ?? "Unable to read Applications sheet.");
  }

  return sheet.rows
    .filter((row) => cell(row, ["Company ID", "CompanyID"], 1) === companyId)
    .map(rowToApplicationStudent);
}

function rowToApplicationStudent(row: Parameters<typeof cell>[0]): RsaApplicationStudent {
  const currentStage = cell(row, ["Current Stage", "Stage"], 7);
  const statusValue = cell(row, ["Status"], 8);
  const status = normalizeApplicationStatus(statusValue, currentStage);
  const remarks = cell(row, ["Remarks"], 12);
  const rejectionReason =
    cell(row, ["Rejection Reason", "Rejected Reason"], 10) ||
    remarks ||
    "Reason not available";
  const selectionReason =
    cell(row, ["Selection Reason", "Selected Reason"]) ||
    remarks ||
    "Reason not available";

  return {
    date: cell(row, ["DATE", "Date"], 0),
    companyId: cell(row, ["Company ID", "CompanyID"], 1),
    companyName: cell(row, ["Company Name"], 2),
    fullName: cell(row, ["Full Name", "Name"], 3),
    email: cell(row, ["Email"], 4),
    phoneNumber: cell(row, ["Phone Number", "Phone", "Mobile Number"], 5),
    resume: cell(row, ["Resume", "Resume URL"], 6),
    currentStage,
    status,
    rejectedRound: cell(row, ["Rejected Round"], 9) || currentStage,
    rejectionReason,
    selectedDate: cell(row, ["Selected Date"], 11),
    selectionReason,
    remarks,
    updatedAt: cell(row, ["Updated At"], 13),
    source: cell(row, ["Source"], 14),
    candidateId: cell(row, ["Candidate ID"], 15),
    studentId: cell(row, ["Student ID"], 16),
    degree: cell(row, ["Degree"], 17),
    branch: cell(row, ["Branch"], 18),
    passoutYear: cell(row, ["Passout Year"], 19),
    percentage: cell(row, ["Percentage"], 20),
    applicationId: cell(row, ["Application ID"], 21),
  };
}

function summarizeApplications(
  applications: RsaApplicationStudent[],
): RsaApplicationsSummary {
  return {
    selectedStudents: applications.filter((item) => item.status === "Selected"),
    rejectedStudents: applications.filter((item) => item.status === "Rejected"),
    inProgressStudents: applications.filter((item) => item.status === "In Progress"),
    droppedStudents: applications.filter((item) => item.status === "Dropped"),
  };
}

function calculateStats(summary: RsaApplicationsSummary): RsaStats {
  return {
    totalApplications:
      summary.selectedStudents.length +
      summary.rejectedStudents.length +
      summary.inProgressStudents.length +
      summary.droppedStudents.length,
    selectedCount: summary.selectedStudents.length,
    rejectedCount: summary.rejectedStudents.length,
    inProgressCount: summary.inProgressStudents.length,
    droppedCount: summary.droppedStudents.length,
  };
}

async function saveRsaReport(input: {
  rsaId?: string;
  company: RsaCompanyDetails;
  adminInputs: RsaAdminInputs;
  stats: RsaStats;
  aiGeneratedRsa: string;
  finalEditedRsa: string;
  status: RsaStatus;
}) {
  const existingReports = await getRsaReportsForCompany(input.company.id);
  const existing = input.rsaId
    ? existingReports.find((report) => report.rsaId === input.rsaId)
    : undefined;
  const now = new Date().toISOString();
  const report: RsaReportRecord = {
    rowNumber: existing?.rowNumber,
    rsaId: input.rsaId || createNextRsaId(input.company.id, existingReports),
    companyId: input.company.id,
    companyName: input.company.name,
    generatedDate: existing?.generatedDate || now,
    generatedBy: existing?.generatedBy || "Admin",
    adminInputs: input.adminInputs,
    stats: input.stats,
    aiGeneratedRsa: input.aiGeneratedRsa,
    finalEditedRsa: input.finalEditedRsa,
    status: input.status,
    confirmedAt:
      input.status === "Confirmed" ? now : existing?.confirmedAt || "",
    updatedAt: now,
  };

  const rowData = reportToRowData(report);
  const sheetResult = existing?.rowNumber
    ? await updateSheetRow({
        sheetTitle: RSA_SHEET_NAME,
        rowNumber: existing.rowNumber,
        startColumn: "A",
        values: RSA_REPORT_HEADERS.map((header) => rowData[header] ?? ""),
      })
    : await appendSheetRow(RSA_SHEET_NAME, rowData, [...RSA_REPORT_HEADERS]);

  if (sheetResult.skipped) {
    throw new Error(sheetResult.reason ?? "Unable to save RSA report.");
  }

  return report;
}

async function readRsaSheet() {
  const setup = await ensureSheetExists(RSA_SHEET_NAME, [...RSA_REPORT_HEADERS]);

  if (setup.skipped) {
    throw new Error(setup.reason ?? "Unable to create RSA_Reports sheet.");
  }

  const sheet = await getSheetRows(RSA_SHEET_NAME);

  if (sheet.skipped) {
    throw new Error(sheet.reason ?? "Unable to read RSA_Reports sheet.");
  }

  return sheet;
}

function rowToRsaReport(row: Parameters<typeof cell>[0]): RsaReportRecord | null {
  const rsaId = cell(row, ["RSA ID"], 0);
  const companyId = cell(row, ["Company ID"], 1);

  if (!rsaId || !companyId) {
    return null;
  }

  return {
    rowNumber: row.rowNumber,
    rsaId,
    companyId,
    companyName: cell(row, ["Company Name"], 2),
    generatedDate: cell(row, ["Generated Date"], 3),
    generatedBy: cell(row, ["Generated By"], 4),
    adminInputs: {
      candidateSharingStrategy: cell(row, ["Candidate Sharing Strategy"], 5),
      interviewFocus: cell(row, ["Interview Focus"], 6),
      companyExpectations: cell(row, ["Company Expectations"], 7),
      trainingGap: cell(row, ["Training Gap"], 8),
      additionalAdminNotes: cell(row, ["Additional Admin Notes"], 9),
      tags: splitTags(cell(row, ["Tags"], 10)),
    },
    stats: {
      totalApplications: toNumber(cell(row, ["Total Applications"], 11)),
      selectedCount: toNumber(cell(row, ["Selected Count"], 12)),
      rejectedCount: toNumber(cell(row, ["Rejected Count"], 13)),
      inProgressCount: toNumber(cell(row, ["In Progress Count"], 14)),
      droppedCount: toNumber(cell(row, ["Dropped Count"], 15)),
    },
    aiGeneratedRsa: cell(row, ["AI Generated RSA"], 16),
    finalEditedRsa: cell(row, ["Final Edited RSA"], 17),
    status: normalizeRsaStatus(cell(row, ["Status"], 18)),
    confirmedAt: cell(row, ["Confirmed At"], 19),
    updatedAt: cell(row, ["Updated At"], 20),
  };
}

function reportToRowData(report: RsaReportRecord) {
  return {
    "RSA ID": report.rsaId,
    "Company ID": report.companyId,
    "Company Name": report.companyName,
    "Generated Date": report.generatedDate,
    "Generated By": report.generatedBy,
    "Candidate Sharing Strategy": report.adminInputs.candidateSharingStrategy,
    "Interview Focus": report.adminInputs.interviewFocus,
    "Company Expectations": report.adminInputs.companyExpectations,
    "Training Gap": report.adminInputs.trainingGap,
    "Additional Admin Notes": report.adminInputs.additionalAdminNotes,
    Tags: report.adminInputs.tags.join(", "),
    "Total Applications": String(report.stats.totalApplications),
    "Selected Count": String(report.stats.selectedCount),
    "Rejected Count": String(report.stats.rejectedCount),
    "In Progress Count": String(report.stats.inProgressCount),
    "Dropped Count": String(report.stats.droppedCount),
    "AI Generated RSA": report.aiGeneratedRsa,
    "Final Edited RSA": report.finalEditedRsa,
    Status: report.status,
    "Confirmed At": report.confirmedAt,
    "Updated At": report.updatedAt,
  };
}

function normalizeApplicationStatus(
  status: string,
  currentStage: string,
): RsaApplicationStudent["status"] {
  const compact = `${status} ${currentStage}`.toLowerCase();

  if (compact.includes("selected")) return "Selected";
  if (compact.includes("rejected")) return "Rejected";
  if (compact.includes("dropped") || compact.includes("drop")) return "Dropped";
  return "In Progress";
}

function normalizeRsaStatus(value: string): RsaStatus {
  const lower = value.toLowerCase();
  if (lower.includes("confirm")) return "Confirmed";
  if (lower.includes("draft")) return "Draft";
  return "Generated";
}

function createNextRsaId(companyId: string, existingReports: RsaReportRecord[]) {
  const date = formatCompactDate(new Date());
  const prefix = `RSA-${companyId}-${date}-`;
  const next =
    existingReports.reduce((highest, report) => {
      if (!report.rsaId.startsWith(prefix)) return highest;
      const sequence = Number(report.rsaId.slice(prefix.length));
      return Number.isFinite(sequence) ? Math.max(highest, sequence) : highest;
    }, 0) + 1;

  return `${prefix}${String(next).padStart(3, "0")}`;
}

function sortReportsNewestFirst(a: RsaReportRecord, b: RsaReportRecord) {
  return timestamp(b.updatedAt || b.generatedDate) - timestamp(a.updatedAt || a.generatedDate);
}

function cell(
  row: Parameters<typeof getSheetCell>[0],
  names: string | string[],
  fallbackIndex?: number,
) {
  return getSheetCell(row, names, fallbackIndex).trim();
}

function splitTags(value: string) {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function toNumber(value: string) {
  return Number(value) || 0;
}

function timestamp(value: string) {
  const parsed = new Date(value).getTime();
  return Number.isNaN(parsed) ? 0 : parsed;
}

function formatCompactDate(date: Date) {
  return [
    date.getFullYear(),
    String(date.getMonth() + 1).padStart(2, "0"),
    String(date.getDate()).padStart(2, "0"),
  ].join("");
}

function firstLine(value: string) {
  return value.split(/\r?\n/).find(Boolean)?.trim() ?? "";
}

function isUrl(value: string) {
  return /^https?:\/\//i.test(value.trim());
}
